version: "3.3"
services:
  phd_api_public_server:
    build: .
    restart: unless-stopped
    image: phd_api_public_server
    container_name: PHDapiPublicServer
    env_file: ./.env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - 6001:6001
